### ISSUE TITLE
importlib.metadata.PackageNotFoundError: autotiling

### ISSUE THREAD

**Issue by mizzunet** [nwg-piotr/autotiling#34]
`autotiling` fails to execute after updating. `autotiling-git-r97.dbdbfa1-1` version works.

```

 ~  autotiling
Traceback (most recent call last):
  File "/usr/bin/autotiling", line 33, in <module>
    sys.exit(load_entry_point('autotiling==1.6', 'console_scripts', 'autotiling')())
  File "/usr/bin/autotiling", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: autotiling
```

```
yay -Qi autotiling
Name            : autotiling
Version         : 1.6-2
Description     : Script for sway and i3 to
                  automatically switch the horizontal /
                  vertical window split orientation
Architecture    : x86_64
URL             : https://github.com/nwg-piotr/autotiling
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : python-i3ipc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 18.50 KiB
Packager        : Chaotic-AUR Wild Bear Node
                  <wildbear.node@chaotic.cx>
Build Date      : Mon 13 Dec 2021 06:39:28 IST
Install Date    : Mon 13 Dec 2021 11:33:05 IST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by nwg-piotr** [comment]
After yesterday's python update, python packages need to be reinstalled, to reflect the new library path. I updated `pkgrel` in the AUR package, but you use Chaotic-AUR, which is apparently out of date. Installing the package once again, over the current install should resolve your issue.

**Comment by dr460nf1r3** [comment]
Hey there, the package has been rebuilt on Chaotic-AUR, so you can do `sudo pacman -Syu autotiling` to fix the issue :)

**Comment by nwg-piotr** [comment]
> the package has been rebuilt on Chaotic-AUR

This should trigger update automagically. Thanks!

**Comment by nwg-piotr** [comment]
@dr460nf1r3 - just in case: same applies to Azote, nwg-wrapper and so on.

**Comment by mizzunet** [comment]
Yep, now it's working. Thanks both of you :)
