### ISSUE TITLE
Python Error when starting the script with Python 3.11

### ISSUE THREAD

**Issue by hnorkowski** [nwg-piotr/autotiling#46]
This error is shown when I run autotiling on Manjaro Linux (up to date) with Python 3.11.3:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/autotiling", line 33, in <module>
    sys.exit(load_entry_point('autotiling==1.8', 'console_scripts', 'autotiling')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/autotiling", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for autotiling
```

**Comment by nwg-piotr** [comment]
Has Manjaro just updated python to 3.11? If so, reinstalling autotiling should help.

**Comment by nwg-piotr** [comment]
This happens to every python package on AUR after python upgrade. I usually trigger re-installations by increasing the package version, but I do it after Arch updates python. Manjaro does it hell knows when.
